[package]
name = "nibarchive"
description = "NIB Archive Decoder/Encoder"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"
authors = ["Michael Wright <maiklpolkovnikov@gmail.com>"]
repository = "https://github.com/michaelwright235/nibarchive"
